version: "3"
services:
  app:
    build: .
    restart: always
    container_name: "torch_cont"
    working_dir: "/root/"
    platform: linux/amd64
    volumes:
      - /local/path:/container/path
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
